### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by deluxghost** [ClassicOldSong/eft-parser#1]
<https://github.com/ClassicOldSong/eft-parser/blame/b94f0a1962ebfaa0a79ac02e25dc438f1d46f244/README.md#L12>

<https://github.com/ClassicOldSong/eft-parser/blame/b94f0a1962ebfaa0a79ac02e25dc438f1d46f244/README.md#L20>

**Comment by ClassicOldSong** [comment]
Typo, will fix later

**Comment by ClassicOldSong** [comment]
Fixed https://github.com/ClassicOldSong/eft-parser/commit/6e5f699304d2830efe9a992cfc665c8e9a78f0f2
